version: '3.7'

services:

  ##
  # The web server container.
  ##
  nginx:
    image: nginx:alpine

    networks:
      - wpdevnet

    ports:
      - ${LOCAL_PORT-8889}:80

    environment:
      LOCAL_DIR: ${LOCAL_DIR-src}

    volumes:
      - ./wordpress/tools/local-env/default.template:/etc/nginx/conf.d/default.template
      - ./wordpress/:/var/www

    # Load our config file, substituting environment variables into the config.
    command: /bin/sh -c "envsubst '$$LOCAL_DIR' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"

    depends_on:
      - php

  ##
  # The PHP container.
  ##
  php:
    image: wordpressdevelop/php:${LOCAL_PHP-latest}

    networks:
      - wpdevnet

    env_file:
      - .env

    environment:
      LOCAL_PHP_XDEBUG: ${LOCAL_PHP_XDEBUG-false}
      LOCAL_PHP_MEMCACHED: ${LOCAL_PHP_MEMCACHED-false}
      PHP_FPM_UID: ${PHP_FPM_UID-1000}
      PHP_FPM_GID: ${PHP_FPM_GID-1000}

    volumes:
      - ./wordpress/tools/local-env/php-config.ini:/usr/local/etc/php/conf.d/php-config.ini
      - ./wordpress/:/var/www

    depends_on:
      - mysql

  ##
  # The MySQL container.
  ##
  mysql:
    image: mysql:${LOCAL_MYSQL-latest}

    networks:
      - wpdevnet

    env_file:
      - .env

    environment:
      MYSQL_ROOT_PASSWORD: password

    volumes:
      - ./wordpress/tools/local-env/mysql-init.sql:/docker-entrypoint-initdb.d/mysql-init.sql
      - mysql:/var/lib/mysql

    # For compatibility with PHP versions that don't support the caching_sha2_password auth plugin used in MySQL 8.0.
    command: --default-authentication-plugin=mysql_native_password

  ##
  # The WP CLI container.
  ##
  cli:
    image: wordpressdevelop/cli:${LOCAL_PHP-latest}

    networks:
      - wpdevnet

    env_file:
      - .env

    environment:
      LOCAL_PHP_XDEBUG: ${LOCAL_PHP_XDEBUG-false}
      LOCAL_PHP_MEMCACHED: ${LOCAL_PHP_MEMCACHED-false}
      PHP_FPM_UID: ${PHP_FPM_UID-1000}
      PHP_FPM_GID: ${PHP_FPM_GID-1000}

    volumes:
      - ./wordpress/:/var/www
      - ./.wp-cli/:/root/.wp-cli

    # The init directive ensures the command runs with a PID > 1, so Ctrl+C works correctly.
    init: true

    depends_on:
      - mysql

  ##
  # The PHPUnit container.
  ##
  phpunit:
    image: wordpressdevelop/phpunit:${LOCAL_PHP-latest}

    networks:
      - wpdevnet

    env_file:
      - .env

    environment:
      LOCAL_PHP_XDEBUG: ${LOCAL_PHP_XDEBUG-false}
      LOCAL_PHP_MEMCACHED: ${LOCAL_PHP_MEMCACHED-false}
      LOCAL_DIR: ${LOCAL_DIR-src}
      WP_MULTISITE: ${WP_MULTISITE-false}
      PHP_FPM_UID: ${PHP_FPM_UID-1000}
      PHP_FPM_GID: ${PHP_FPM_GID-1000}

    volumes:
      - ./wordpress/tools/local-env/phpunit-config.ini:/usr/local/etc/php/conf.d/phpunit-config.ini
      - ./wordpress/:/var/www
      - ./wordpress/phpunit-uploads:/var/www/${LOCAL_DIR-src}/wp-content/uploads

    # The init directive ensures the command runs with a PID > 1, so Ctrl+C works correctly.
    init: true

    depends_on:
      - mysql

volumes:
  mysql: {}
  # Using a volume for the uploads directory improves PHPUnit performance.
  phpunit-uploads: {}

networks:
  # Creating our own network allows us to connect between containers using their service name.
  wpdevnet:
    driver: bridge
